package com.caocao.cadavimusicplayer.util

import androidx.core.net.toUri

val ArtURI = "content://media/external/audio/albumart".toUri()

object ArgumentUtil {
    const val ARGUMENT_ID_ARTIST = "ARGUMENT_ID_ARTIST"
    const val ARGUMENT_NAME_ARTIST = "ARGUMENT_NAME_ARTIST"
    const val ARGUMENT_COUNT_ARTIST = "ARGUMENT_COUNT_ARTIST"
    const val ARGUMENT_ID_ALBUMS = "ARGUMENT_ID_ALBUMS"
    const val ARGUMENT_NAME_ALBUMS = "ARGUMENT_NAME_ALBUMS"
    const val ARGUMENT_COUNT_ALBUMS = "ARGUMENT_COUNT_ALBUMS"
    const val ARGUMENT_ARTIST_ALBUMS = "ARGUMENT_ARTIST_ALBUMS"
    const val ARGUMENT_ID_GENRE = "ARGUMENT_ID_GENRE"
    const val ARGUMENT_NAME_GENRE = "ARGUMENT_NAME_GENRE"
    const val ARGUMENT_COUNT_GENRE = "ARGUMENT_COUNT_GENRE"
    const val ARGUMENT_ID_PLAYLIST = "ARGUMENT_ID_PLAYLIST"
    const val ARGUMENT_NAME_PLAYLIST = "ARGUMENT_NAME_PLAYLIST"
    const val ARGUMENT_ID_SONG_PLAYLIST= "ARGUMENT_ID_SONG_PLAYLIST"
}